### ISSUE TITLE
w60x Arduino Framework not working

### ISSUE THREAD

**Issue by ProchyMicrochip** [maxgerhardt/platform-w60x#1]
Examples for arduino framework are not working.

**Comment by maxgerhardt** [comment]
Tested on which board? 

Compiling + upload works, but example doesn't run?

**Comment by ProchyMicrochip** [comment]
When running without modification throws:
`Error: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ ~1.40903.0'`
`requirements for your system 'windows_amd64'`

fixed by:
`[env:generic_w600]`
`platform_packages = platformio/toolchain-gccarmnoneeabi@^1.100301.220327`
`platform = w60x`
`board = generic_w600`
`framework = arduino`

then trows Linking Error
`collect2.exe: error: ld returned 1 exit status`
`*** [.pio\build\generic_w600\firmware.elf] Error 1`

**Comment by maxgerhardt** [comment]
https://github.com/maxgerhardt/platform-w60x/network shows there are forks which have fixed this error.
Does it work when remove your platform_packages and set 
```
platform = https://github.com/choryuidentify/platform-w60x.git
```
instead?

**Comment by ProchyMicrochip** [comment]
This fork works fine, builds without error, but still cant upload to Wemos W600-PICO. But I think i can figure that out.
Thanks for quick support

**Comment by maxgerhardt** [comment]
I've imported the build fix via https://github.com/maxgerhardt/platform-w60x/commit/f8447b1f87b6cbf0d136273b73728b559d4742b0.

You have to connect the bootloader pin PA0 to GND and reset the board (usually via a reset button, but could also power cycle it) to get into the bootloader mode where you can flash it. See [wm_w60x_firmware_update_guide_v1.2.pdf](https://github.com/maxgerhardt/platform-w60x/files/9905006/wm_w60x_firmware_update_guide_v1.2.pdf) page 6.
